name: Fmt and Clippy

# This job runs rustfmt and clippy linting,

on:
  push:
    branches: main
    paths: [concordium_contracts/**]

  pull_request:
    branches: main
    paths: [concordium_contracts/**]

  workflow_dispatch: # allows manual trigger

env:
  RUST_FMT: nightly-2022-06-09-x86_64-unknown-linux-gnu
  RUST_CLIPPY: 1.67

jobs:
  "lint_fmt":
    name: lint:fmt
    # Don't run on draft pull requests
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_FMT }}
          override: true
          components: rustfmt
      - name: Format
        run: |
          cargo fmt --manifest-path concordium_contracts/deploy-scripts/Cargo.toml -- --color=always --check
          cargo fmt --manifest-path concordium_contracts/bridge-manager/Cargo.toml -- --color=always --check
          cargo fmt --manifest-path concordium_contracts/cis2-bridgeable/Cargo.toml -- --color=always --check

  "lint_clippy":
    name: lint:clippy
    needs: "lint_fmt"
    # Don't run on draft pull requests
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_CLIPPY }}
          override: true
          target: ${{ env.TARGET }}
          components: rustfmt, clippy
      - name: Clippy
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          cargo clippy --manifest-path concordium_contracts/deploy-scripts/Cargo.toml --color=always --tests --benches -- -Dclippy::all
          cargo clippy --manifest-path concordium_contracts/bridge-manager/Cargo.toml --color=always --tests --benches -- -Dclippy::all
          cargo clippy --manifest-path concordium_contracts/cis2-bridgeable/Cargo.toml --color=always --tests --benches -- -Dclippy::all

  "test_contracts":
    name: test:contracts
    needs: "lint_clippy"
    # Don't run on draft pull requests
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_CLIPPY }}
          override: true
          target: ${{ env.TARGET }}
          components: rustfmt, clippy
      - name: Clippy
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          cargo test --manifest-path concordium_contracts/bridge-manager/Cargo.toml
          cargo test --manifest-path concordium_contracts/cis2-bridgeable/Cargo.toml

  compile-no-std:
    name: compile:no-std
    runs-on: ubuntu-latest
    needs: "lint_clippy"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install nightly toolchain with check available
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true

      - name: Run cargo build with no-std
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          cargo +nightly concordium build -e --manifest-path concordium_contracts/bridge-manager/Cargo.toml -- --no-default-features --features wee_alloc
          cargo +nightly concordium build -e --manifest-path concordium_contracts/cis2-bridgeable/Cargo.toml -- --no-default-features --features wee_alloc
